hotline/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

from __future__ import (unicode_literals, absolute_import,
                        division, print_function)

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'dispatcher.views.dashboard', name='home'),
    url(r'^sms$', 'dispatcher.views.sms_check', name='sms'),
    url(r'^sms/(?P<event_filter>[A-Z\_]+)$', 'dispatcher.views.sms_check', name='sms_filter'),
    url(r'^sms/(?P<event_id>[0-9]+)/(?P<new_type>[A-Za-z\_]+)/(?P<return_to>[A-Z\_]+)$', 'dispatcher.views.sms_change_type', name='sms_change_type'),

     # # Android API
    url(r'^fondasms/?$', 'fondasms.views.fondasms_handler',
        {'handler_module': 'dispatcher.fondasms_handlers',
         'send_automatic_reply': True,
         'automatic_reply_via_handler': False,
         'automatic_reply_text': ("Merci de votre appel. La Hotline "
                                  "SOS Démocratie vous rappelle bientôt.")},
        name='fondasms'),
    url(r'^tester/?$', 'fondasms.views.fondasms_tester',
        name='fondasms_tester'),

    # url(r'^smssync$', 'dispatcher.views.smssync', name='smssync'),
    # url(r'^ringsync$', 'dispatcher.views.ringsync_status', name='ringsync_status'),
    # url(r'^ringsync/(?P<call_number>[\+a-z0-9A-Z\-\.\_]+)/(?P<call_timestamp>[0-9]+)/?$',
    #     'dispatcher.views.ringsync', name='ringsync'),

    url(r'^password/?$', 'dispatcher.views.change_password', name='changepwd'),

    url(r'^data-entry$', 'dispatcher.views.data_entry', name='data_entry'),

    url(r'^blacklist$', 'dispatcher.views.blacklist', name='blacklist'),

    url(r'^status$', 'dispatcher.views.status', name='status'),
    url(r'^export$', 'dispatcher.views.exported_status', name='export'),
    url(r'^import_event$', 'dispatcher.views.import_event', name='import_event'),
    url(r'^graph_data/$', 'dispatcher.views.graph_data', name='graph_data'),

    url(r'^entities/(?P<parent_slug>\d{8})/?$', 'dispatcher.views.entities_api', name='entities'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

dispatcher/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

from __future__ import (unicode_literals, absolute_import,
                        division, print_function)
import json
import datetime


from django import forms
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from batbelt import to_timestamp

from dispatcher.models import (HotlineEvent, HotlineVolunteer, HotlineResponse,
                               Topics, Entity, BlackList, ResponseSMS)
from dispatcher.utils import (NB_NUMBERS, NB_CHARS_HOTLINE,
                              operator_from_mali_number,
                              clean_phone_number,
                              make_ushahidi_request,
                              is_valid_number,
                              send_notification,
                              operators, ANSWER, COUNTRY_PREFIX,
                              join_phone_number,
                              number_is_blacklisted,
                              datetime_range,
                              count_unarchived_sms,
                              get_default_context, stats_per_age,
                              EMPTY_ENTITY, topic_stats_details, regions_located_responses,
                              import_hotine_events)


@login_required()
def dashboard(request):

    context = get_default_context(page='dashboard')

    context.update({'operators':
                    [(operator, HotlineEvent.objects.filter(operator=operator,
                                                            processed=False,
                                                            event_type__in=HotlineEvent.HOTLINE_TYPES).count())
                     for operator in operators()]})

    if request.method == 'POST':

        try:
            nb_numbers = int(request.POST.get('nb_numbers', NB_NUMBERS))
        except ValueError:
            nb_numbers = NB_NUMBERS

        operator = request.POST.get('operator_request')
        if not operator in operators():
            context.update({'error': "L'opérateur demandé (%s) "
                                     "n'est pas correct" % operator})

        events = HotlineEvent.objects.filter(operator=operator,
                                             processed=False,
                                             event_type__in=HotlineEvent.HOTLINE_TYPES) \
                                     .order_by('received_on')[:nb_numbers]

        for event in events:
            event.processed = True
            event.volunteer = request.user
            event.save()

        context.update({'events': events,
                        'requested': True,
                        'operator': operator,
                        # 'user_number': user_number,
                        'nb_numbers': nb_numbers})

    return render(request, "dashboard.html", context)


@login_required()
def sms_check(request, event_filter=HotlineEvent.TYPE_SMS_UNKNOWN):

    context = get_default_context(page='sms')

    if not event_filter in HotlineEvent.SMS_TYPES:
        event_filter = HotlineEvent.TYPE_SMS_UNKNOWN

    try:
        nb_numbers = int(request.POST.get('nb_numbers', NB_NUMBERS))
    except ValueError:
        nb_numbers = NB_NUMBERS
    events = HotlineEvent.objects.filter(processed=False,
                                         event_type=event_filter) \
                                 .order_by('-received_on')[:nb_numbers]

    context.update({'events': events,
                    'filter': event_filter,
                    'filters': [(HotlineEvent.TYPE_SMS_UNKNOWN, "À Trier"),
                                (HotlineEvent.TYPE_SMS_HOTLINE, "Hotline"),
                                (HotlineEvent.TYPE_SMS_USHAHIDI, "Ushahidi"),
                                (HotlineEvent.TYPE_CHARGE_ME, "Peux-tu recharger mon compte?"),
                                (HotlineEvent.TYPE_SMS_SPAM, "SPAM")],
                    'requested': True,
                    'nb_numbers': nb_numbers})

    return render(request, "sms_check.html", context)


@login_required()
def sms_change_type(request, event_id, new_type,
                    return_to=HotlineEvent.TYPE_SMS_UNKNOWN):

    try:
        event = HotlineEvent.objects.get(id=int(event_id))
        event.event_type = new_type
        event.save()
    except (HotlineEvent.DoesNotExist, ValueError):
        pass

    if event and event.event_type == HotlineEvent.TYPE_SMS_USHAHIDI:
        make_ushahidi_request(event)

    return redirect('sms_filter', return_to)


@login_required()
def change_password(request):
    context = get_default_context(page='password')

    class ChangePasswordForm(forms.Form):

        old_password = forms.CharField(label="Mot de passe actuel",
                                       max_length=100,
                                       widget=forms.PasswordInput)
        new_password = forms.CharField(label="Nouveau mot de passe",
                                       max_length=100,
                                       widget=forms.PasswordInput)
        new_password_verify = forms.CharField(label="Nouveau mot de passe (vérification)",
                                              max_length=100, widget=forms.PasswordInput)

        def clean(self):
            cleaned_data = super(ChangePasswordForm, self).clean()

            new_password = cleaned_data.get('new_password')
            new_password_verify = cleaned_data.get('new_password_verify')

            if new_password != new_password_verify:
                raise forms.ValidationError("Les nouveaux mot de passe ne sont pas identiques")
            return cleaned_data

        def clean_old_password(self):
            old_password = self.cleaned_data.get('old_password')
            if not request.user.check_password(old_password):
                raise forms.ValidationError("Mot de passe incorrect.")

    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            request.user.set_password(form.cleaned_data['new_password'])
            request.user.save()
            messages.success(request, "Le mot de passe a été changé.")
            return redirect('home')
    else:
        form = ChangePasswordForm()

    context.update({'form': form})

    return render(request, "change_password.html", context)


@login_required()
def data_entry(request):
    ''' Enter Data for calls made by the volunteers

        Step 1: Pick a volunteer to enter data for.
        Step 2: List all calls made by the chosen volunteer
        Step 3: Enter data for a specific call.
        This creates a HotlineResponse object. '''

    class HotlineResponseForm(forms.Form):
        ''' Used to easily enter data for calls made by volunteers. '''

        request_id = forms.IntegerField(widget=forms.HiddenInput)
        response_date = forms.DateTimeField(label="Date de l'appel",
                                            help_text="Format: JJ/MM/AAAA",
                                            widget=forms.SplitDateTimeWidget)
        duration = forms.IntegerField(label="Durée (approx.)",
                                      help_text="En nombre de minutes arrondis "
                                                "(ex. 2 pour 1min:35s et 1 pour 1min:29s)")
        topics = forms.MultipleChoiceField(label="Questions",
                                           choices=[(t.slug, t.display_name())
                                           for t in Topics.objects.order_by('slug')],
                                           widget=forms.CheckboxSelectMultiple)
        age = forms.IntegerField(label="Age", required=False)
        sex = forms.ChoiceField(label="Sexe", choices=HotlineResponse.SEXES.items(),
                                required=False, initial=HotlineResponse.SEX_UNKNOWN)
        region = forms.ChoiceField(label="Région",
                                   choices=[(EMPTY_ENTITY, "INCONNUE")] + [(e.slug, e.name)
                                   for e in Entity.objects.filter(type=Entity.TYPE_REGION)])
        cercle = forms.CharField(label="Cercle", widget=forms.Select, required=False)
        commune = forms.CharField(label="Commune", widget=forms.Select, required=False)
        village = forms.CharField(label="Village", widget=forms.Select, required=False)

        def clean_village(self):
            ''' Returns a Village Entity from the multiple selects '''
            is_empty = lambda l: l is None or l == EMPTY_ENTITY
            location = None
            levels = ['region', 'cercle', 'commune', 'village']
            while len(levels) and is_empty(location):
                location = self.cleaned_data.get(levels.pop()) or None

            if is_empty(location):
                return None

            try:
                return Entity.objects.get(slug=location)
            except Entity.DoesNotExist:
                raise forms.ValidationError("Localité incorrecte.")

        def clean_request_id(self):
            ''' Return a HotlineEvent from the id '''
            try:
                return HotlineEvent.objects.get(id=int(self.cleaned_data.get('request_id')))
            except HotlineEvent.DoesNotExist:
                raise forms.ValidationError("Évennement incorrect")

    context = get_default_context(page='data_entry')
    context.update({'volunteers': [(vol, HotlineEvent.objects.filter(volunteer=vol,
                                                                     processed=True,
                                                                     answer__isnull=True).count())
                                   for vol in HotlineVolunteer.objects.filter(is_active=True)]})

    volunteer = None
    events = []

    # Send volunteer to template if it's in GET
    if request.GET.get('volunteer'):

dispatcher/templates/base.html
{% load dispatcher %}
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Hotline - SOS Démocratie</title>
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="/static/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/css/imgareaselect-default.css" />
<link href="/static/css/hotline.css" rel="stylesheet">
<link href="/static/css/flot.css" rel="stylesheet">
</head>
<body class="{{ page }}">
<div class="container">

<div class="row-fluid">
<div class="span8">
<h1>Hotline SOS Démocratie</h1>
<div class="btn-group">
	<button class="btn btn-small link {% ifequal page 'dashboard' %}active{% endifequal %}" href="{% url 'home' %}" title="Récupération numéros">Numéros <span class="label label-info">{{ nbunprocessed }}</span></button>
	<button class="btn btn-small link {% ifequal page 'sms' %}active{% endifequal %}" href="{% url 'sms' %}" title="Ventillation SMS">SMS <span class="label label-info">{{ nbsms }}</span></button>
	<button class="btn btn-small link {% ifequal page 'data_entry' %}active{% endifequal %}" href="{% url 'data_entry' %}">Saisie Appels <span class="label label-info">{{ nbarchive }}</span></button>
    <button class="btn btn-small link {% ifequal page 'status_page' %}active{% endifequal %}" href="{% url 'status' %}">Statut</button>
	<button class="btn btn-small link {% ifequal page 'blacklist' %}active{% endifequal %}" href="{% url 'blacklist' %}">Liste noire</button>
    <button class="btn btn-small link label label-warning" href="{% url 'import_event' %}" title="Import CSV">Import CSV</button>
    <button class="btn btn-small link label label-warning" href="{% url 'logout' %}" title="Déconnexion ({{ user }})"><i class="icon icon-user"></i> Déconnexion</button>
	<button class="btn btn-small link {% ifequal page 'password' %}active{% endifequal %}" href="{% url 'changepwd' %}" title="Changer mot de passe">Mot de passe</button>
</div>
</div>
<div class="span4" style="text-align:right;">
<h2 style="color:orange;">91 16 16 76</h2>
<h2 style="color:blue;">67 56 52 52</h2>
</div>
</div>
{% if messages %}
<div class="messages" style="float: right;">
{% for message in messages %}<p {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</p>{% endfor %}
</div>
{% endif %}
{% block content %}
{% endblock %}
</div>

<script type="text/javascript" src="/static/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script src="static/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.flot.js"></script>
<script type="text/javascript" src="/static/js/jquery.flot.time.js"></script>
<script type="text/javascript" src="/static/js/jquery.flot.selection.js"></script>
<script type="text/javascript">
$(document).ready(function (){
	$('.link').click(function () {
		window.location = $(this).attr('href');
	})

	var sms_filter_url = "{%url 'sms_filter' 'AAA' %}";
	$('.delete-confirm').click(function(e) {
	  // e.preventDefault();
	  target = $(e.target);
	  return confirm("Êtes vous sûr de vouloir SUPPRIMER le SMS/#"+ target.attr('event_id') +" de "+ target.attr('event_identity') +" ?");

	});

	$('.btn-filter').click(function (){
		var filter = $(this).attr('filter');
		var new_url = sms_filter_url.replace('AAA', filter);
		console.log(new_url);
		window.location = new_url;
	});

	function changeSelectContent(selectElement, content) {
		selectElement.empty();
		$.each(content, function (idx, entity) {
			selectElement.append($("<option value='"+entity.slug +"'>" + entity.name + "</option>"));
		});
	}

	function changeRegion(regionElem, cercle_id, commune_id, village_id) {
		var region_id = regionElem.val();
		var cercle = $('#id_cercle');
		$.getJSON('/entities/' + region_id).done(function (response) {
			changeSelectContent(cercle, response);
			if (cercle_id !== undefined && cercle_id !== null) {
				cercle.val(cercle_id);
			}
			changeCercle(cercle, commune_id, village_id);
		});
	}

	function changeCercle(cercleElem, commune_id, village_id) {
		var cercle_id = cercleElem.val();
		var commune = $('#id_commune');
		$.getJSON('/entities/' + cercle_id).done(function (response) {
			changeSelectContent(commune, response);
			if (commune_id !== undefined && commune_id !== null) {
				commune.val(commune_id);
			}
			changeCommune(commune, village_id);
		});
	}

	function changeCommune(communeElem, village_id) {
		var commune_id = communeElem.val();
		var village = $('#id_village');
		$.getJSON('/entities/' + commune_id).done(function (response) {
			changeSelectContent(village, response);
			if (village_id !== undefined && village_id !== null) {
				village.val(village_id);
			}
		});
	}

	function fill_from_previous() {
		var cercle_id = $('#previous_cercle').val();
		var commune_id = $('#previous_commune').val();
		var village_id = $('#previous_village').val();
		if (cercle_id !== undefined && cercle_id !== null) {
			changeRegion($('#id_region'), cercle_id, commune_id, village_id);
		}
	}

	$('#id_region').change(function () {
		var region_id = $(this).val();
		var cercle = $('#id_cercle');
		console.log("Changed region: " + region_id);
		$.getJSON('/entities/' + region_id).done(function (response) {
			changeSelectContent(cercle, response);
			changeCercle($("#id_cercle"));
		});
	});

	$('#id_cercle').change(function () {
		changeCercle($(this));
	});

	$('#id_commune').change(function () {
		changeCommune($(this));
	});

	{% block extra_js %}{% endblock %}
});
</script>
</body>
</html>

dispatcher/templates/base_export.html
{% load dispatcher %}
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Hotline - SOS Démocratie</title>
<link href="static/css/bootstrap.min.css" rel="stylesheet">
<link href="static/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="static/css/hotline.css" rel="stylesheet">
<link href="static/css/flot.css" rel="stylesheet">
</head>
<body class="{{ page }}">
<div class="container">

<div class="row-fluid">
<div class="span8">
<h1>Hotline SOS Démocratie</h1>
</div>
<div class="span4" style="text-align:right;">
<h2 style="color:orange;">91 16 16 76</h2>
<h2 style="color:blue;">67 56 52 52</h2>
</div>
</div>
{% block content %}
{% endblock %}
</div>

<script type="text/javascript" src="static/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="static/js/jquery.flot.js"></script>
<script type="text/javascript" src="static/js/jquery.flot.time.js"></script>
<script type="text/javascript" src="static/js/jquery.flot.selection.js"></script>
<script type="text/javascript">
$(document).ready(function (){
    {% block extra_js %}{% endblock %}
});
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42545659-1', 'opendata.ml');
  ga('send', 'pageview');

</script>
</body>
</html>

dispatcher/templates/blacklist.html
{% extends "base.html" %}
{% load dispatcher %}

{% block content %}

<form class="form-inline" method="post" action="{% url 'blacklist' %}">
{% csrf_token %}
<legend>Ajouter un numéro dans la liste noire</legend>
<input type="text" class="input" name="identity" placeholder="Numéro à ajouter" />
<button type="submit" class="btn btn-alert">Ajouter</button>
</form>

<h2>Liste des numéros de la liste noire</h2>
<ul>
{% for blacknum in blacknums %}
<li>{{ blacknum.identity|phone }} <span class="label label-inverse">{{ blacknum.call_count }}</span></li>
{% empty %}
<li>Aucun numéro dans la liste !</li>
{% endfor %}
</ul>

{% endblock %}

dispatcher/templates/change_password.html
{% extends "base.html" %}

{% block content %}

<form class="form-inline" method="post" action="{% url 'changepwd' %}">
{% csrf_token %}
<legend>Changement de mot de passe</legend>
{{ form.as_p}}
<input type="submit" class="btn btn-primary" value="Changer le mot de passe" />
</form>

{% endblock %}

dispatcher/templates/dashboard.html
{% extends "base.html" %}
{% load dispatcher %}

{% block content %}

<form class="form-inline" method="POST" action="{% url 'home' %}">
{% csrf_token %}
<legend>À remplir par le volontaire</legend>
<p class="alert alert-info"><strong>Attention !</strong> Assurez vous de pouvoir noter les numéros avant d'en faire la demande. Il seront immédiatement signalés comme <em>traités par vous</em>. Merci !</p>

<select name="operator_request">
{% for op_name, op_count in operators %}<option value="{{ op_name }}">{{ op_name|upper }}: {{ op_count }}</option>{% endfor %}</select>
<input type="number" class="input-small" name="nb_numbers" value="5" />
<button type="submit" class="btn">Demander des numéros</button>
</form>

{% if error %}
<p class="alert alert-error">{{ error }}</p>
{% endif %}

{% if requested and not error %}
<div class="received_numbers">
<legend>Vos numéros à appeler ({{ user }})</legend>
	{% if events %}
	<table class="table table-condensed table-hover table-bordered table-striped">
	<caption>Numéro à appeller</caption>
	<thead>
	<tr>
	<th class="span2">Date &amp; Heure</th>
	<th class="span2">Numéro</th>
	<th class="span6">Type &amp; Message (SMS)</th>
	<th class="span2">Volontaire</th>
	</tr>
	</thead>
	<tbody>
	{% for event in events %}
		<tr><td>{{ event.received_on }}</td>
			<td><strong>{{ event.identity|phone }}</strong></td>
			<td><strong>{{ event.event_type }}</strong>{% if event.sms_message %}<br />{{ event.sms_message|default_if_none:"" }}{% endif %}</td>
			<td>{{ user }} / {{operator|upper}}</td></tr>
	{% endfor %}
	</tbody>
	</table>
	{% else %}
	<p class="alert alert-warning">Aucun numéro à appeler pour le moment pour <strong>{{ operator|upper }}</strong></p>
	{% endif %}
	</div>
{% endif %}
{% endblock %}

dispatcher/templates/import_event.html
{% extends "base.html" %}
{% load dispatcher %}

{% block content %}
<div id="context">
<p>Cliquez sur <em>Parcourir…</em> et sélectionnez le fichier CSV que vous souhaitez ajouter.</p>

{% if result %}
{% if success %}
<p class="alert alert-success">Fichier importé avec succes. {{nbok}} evenements crées</p>
{% else %}
<p class="alert alert-error">{{ error_message }}. {{nbok}} appels crées</p>
{% endif %}
{% endif %}

<form method="POST" action="{% url 'import_event' %}" name="import_event" enctype="multipart/form-data">
{% csrf_token %}
<input name="csv_file" type="file" />
<input type="submit" value="Envoyer le fichier" />
</form>

{% endblock %}

dispatcher/templates/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form class="form-inline" method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<legend>Identification</legend>
<p>Identifiant: {{ form.username }}</p>
<p>Mot de passe: {{ form.password }}</p>
<input type="submit" class="btn btn-primary" value="S'identifier" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

dispatcher/templates/stats_per_age.html
{% load dispatcher %}

<h2>Répartition des rappels par tranche d'âge</h2>
    <table class="table table-condensed table-hover table-bordered table-striped table-info">
    <thead>
    <tr>
    <th class="span2">Tranche d'âge</th>
    <th class="span2">Taux (nombre)</th>
    </tr>
    </thead>
    <tbody>
    <tr><td>moins de 18</td>
        <td><strong>{{ under_18.1|floatformat:2 }}% ({{ under_18.0 }})</strong></td>
    </tr>
    <tr><td>de 19 à 25</td>
        <td><strong>{{ stats_19_25.1|floatformat:2 }}% ({{ stats_19_25.0 }})</strong></td>
    </tr>
    <tr><td>de 26 à 30</td>
        <td><strong>{{ stats_26_30.1|floatformat:2 }}% ({{ stats_26_30.0 }})</strong></td>
    </tr>
    <tr><td>de 31 à 35</td>
        <td><strong>{{ stats_31_35.1|floatformat:2 }}% ({{ stats_31_35.0 }})</strong></td>
    </tr>
    <tr><td>de 36 à 40</td>
        <td><strong>{{ stats_36_40.1|floatformat:2 }}% ({{ stats_36_40.0 }})</strong></td>
    </tr>
    <tr><td>de 41 à 45</td>
        <td><strong>{{ stats_41_45.1|floatformat:2 }}% ({{ stats_41_45.0 }})</strong></td>
    </tr>
    <tr><td>de 46 à 50</td>
        <td><strong>{{ stats_46_50.1|floatformat:2 }}% ({{ stats_46_50.0 }})</strong></td>
    </tr>
    <tr><td>de 51 à 55</td>
        <td><strong>{{ stats_55_56.1|floatformat:2 }}% ({{ stats_55_56.0 }})</strong></td>
    </tr>
    <tr><td>56 et plus</td>
        <td><strong>{{ other_56.1|floatformat:2 }}% ({{ other_56.0 }})</strong></td>
    </tr>
    <tr><td>Inconnus</td>
        <td><strong>{{ unknown_age_percent|floatformat:2 }}% ({{ unknown_age }})</strong></td>
    </tr>
    </tbody>
    </table>

dispatcher/templates/status.html
{% extends "base.html" %}
{% load dispatcher %}

{% block content %}

{% include "status_infos_table.html" %}

{% include "status_region_table.html" %}

{% include "stats_per_age.html" %}

{% include "status_topics_table.html" %}

{% include "status_events_graph.html" %}

{% endblock %}

{% block extra_js %}
    {% url 'graph_data' as graph_url %}
    {% include "status_events_graph.js" with graph_data_url=graph_url %}
{% endblock %}

dispatcher/templates/status_for_export.html
{% extends "base_export.html" %}
{% load dispatcher %}

{% block content %}

<div class="alert alert-info">
<p>Cette page présente les données de la <strong>Hotline SOS Démocratie</strong> à un instant <em>t</em>.</p>
<p>Elle devrait être mise à jour quotidiennement (vers 17h) pendant toute la durée du projet.</p>
<p>Les données brutes complète sont disponible sur <a href="http://opendata.ml">Open Data Mali</a>.</p>
</div>

{% include "status_infos_table.html" %}

{% include "status_region_table.html" %}

{% include "stats_per_age.html" %}

{% include "status_topics_table.html" %}

{% include "status_events_graph.html" %}

<div class="sponsors">
    <a href="http://opendata.ml"><img src="static/img/opendata.png" /></a>
    <a href="http://usaid.gov"><img src="static/img/usaid.png" /></a>
    <a href="http://sosdemocratiemali.org"><img src="static/img/sosdemo.jpg" /></a>
</div>

{% endblock %}

{% block extra_js %}
    {% include "status_events_graph.js" with graph_data_url='graph_data.json' %}
{% endblock %}

dispatcher/templates/status_region_table.html
{% load dispatcher %}

{% if regions_located_responses %}
<h2>Répartition des rappels par région</h2>
    <table class="table table-condensed table-hover table-bordered table-striped table-info">
    <thead>
    <tr>
    <th class="span2">Région</th>
    <th class="span2">Taux (nombre)</th>
    </tr>
    </thead>
    <tbody>
    {% for region, count, percent in regions_located_responses %}
        <tr><td>{{ region }}</td>
            <td><strong>{{ percent|floatformat:2 }}% ({{ count }})</strong></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endif %}